### ISSUE TITLE
Unable authenticate with created username/password

### ISSUE THREAD

**Issue by frenchbread** [apinf/emq-rest-api#3]
Unable to authenticate with `username: admin; password: test12345` - 403 response code.

Running Sails app via:
```
sails_permissions__adminUsername='admin' sails_permissions__adminPassword='test12345' sails lift --models.migrate='alter' --port=1339
```

Check that item was created:

![screen shot 2017-02-23 at 17 48 05](https://cloud.githubusercontent.com/assets/2122679/23266360/40fab6ea-f9f0-11e6-85d3-fb648c1804cc.png)

If creating different admin user, e.g. `admin1`, following error pops up:
```
info: sails-permissions: admin user does not exist; creating...
debug: Error (E_VALIDATION) :: 1 attribute is invalid
error: duplicate key value violates unique constraint "user_email_key"
    at Connection.parseE (/home/damir/apps/emq-rest-api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/damir/apps/emq-rest-api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/damir/apps/emq-rest-api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

Invalid attributes sent to undefined:
 • email
   • A record with that `email` already exists (`admin@example.com`).

error: { [Error]
  originalError:
   Error (E_VALIDATION) :: 1 attribute is invalid
   error: duplicate key value violates unique constraint "user_email_key"
       at Connection.parseE (/home/damir/apps/emq-rest-api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
       at Connection.parseMessage (/home/damir/apps/emq-rest-api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
       at Socket.<anonymous> (/home/damir/apps/emq-rest-api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:551:20)

   Invalid attributes sent to undefined:
    • email
      • A record with that `email` already exists (`admin@example.com`).
   ,
  reason: 'NaN attributes are invalid',
  code: 'E_VALIDATION',
  status: 400,
  invalidAttributes: { email: [ [Object] ] } }
```

**Comment by brylie** [comment]
After you run the app for the first time, you can just launch it with `sails lift`. In effect, you only need to create the admin user once.

**Comment by frenchbread** [comment]
@brylie Yep, that's another question. 

The scenario, when there is a need to add more admin users, it is kind of tricky.

But the main issue here is that the authentication does not work now. Are you able to reproduce?

**Comment by brylie** [comment]
> Running Sails app via:
>```
>sails_permissions__adminUsername='admin' sails_permissions__adminPassword='test12345' sails lift --models.migrate='alter' --port=1339
>```

How are you running the Sails app? Did you try authenticating when running like this:

```
sails lift
```

**Comment by brylie** [comment]
Try resetting the database, and running the `sails lift` with the admin credentials **only once**.

**Comment by frenchbread** [comment]
Thanks. Everything work after DB reset. But anyway it's weird that adding more admin users is not "out of the box" supported.
